# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0051_corrida_local_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='cidade',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pago',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
