# Generated by Codex on 2026-06-29

import django.db.models.deletion
from django.db import migrations, models


def criar_percursos_padrao(apps, schema_editor):
    Corrida = apps.get_model('api_s', 'Corrida')
    Inscricao = apps.get_model('api_s', 'Inscricao')
    PercursoCorrida = apps.get_model('api_s', 'PercursoCorrida')

    for corrida in Corrida.objects.all().iterator():
        percurso, _ = PercursoCorrida.objects.get_or_create(
            corrida_id=corrida.id,
            nome="Percurso unico",
            defaults={
                "ativo": True,
                "ordem": 0,
            },
        )
        Inscricao.objects.filter(
            corrida_id=corrida.id,
            percurso_id__isnull=True,
        ).update(percurso_id=percurso.id)


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0052_participante_cidade_inscricao_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercursoCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('distancia_km', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percursos', to='api_s.corrida')),
            ],
            options={
                'verbose_name': 'Percurso da corrida',
                'verbose_name_plural': 'Percursos da corrida',
                'ordering': ['ordem', 'distancia_km', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='inscricao',
            name='percurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='api_s.percursocorrida'),
        ),
        migrations.RunPython(criar_percursos_padrao, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='inscricao',
            name='percurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='api_s.percursocorrida'),
        ),
        migrations.AddConstraint(
            model_name='percursocorrida',
            constraint=models.UniqueConstraint(fields=('corrida', 'nome'), name='unique_percurso_por_corrida'),
        ),
        migrations.AddIndex(
            model_name='percursocorrida',
            index=models.Index(fields=['corrida', 'ativo', 'ordem'], name='api_s_percu_corrida_412679_idx'),
        ),
    ]
