# Generated by Codex on 2026-06-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0053_percursocorrida_inscricao_percurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoexcel',
            name='percurso',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='resultado',
                to='api_s.percursocorrida',
            ),
        ),
    ]
