# Generated by Codex on 2026-06-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0054_arquivoexcel_percurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='numero_chip',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='ResultadoInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.CharField(max_length=30)),
                ('posicao_geral', models.PositiveIntegerField()),
                ('colocacao_categoria', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_cronometragem', to='api_s.inscricao')),
            ],
            options={
                'verbose_name': 'Resultado de inscrição',
                'verbose_name_plural': 'Resultados de inscrições',
                'indexes': [
                    models.Index(fields=['posicao_geral'], name='api_s_resul_posicao_7a2305_idx'),
                    models.Index(fields=['colocacao_categoria'], name='api_s_resul_colocac_b85d06_idx'),
                ],
            },
        ),
    ]
