# Generated by Django 5.2.7 on 2026-06-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0056_alter_inscricao_percurso_delete_behavior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corrida',
            options={'verbose_name': 'Corrida', 'verbose_name_plural': 'Corridas'},
        ),
    ]
