# Generated by Django 5.2.7 on 2026-06-29 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0057_alter_corrida_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoexcel',
            name='corrida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='api_s.corrida'),
        ),
        migrations.AlterField(
            model_name='arquivoexcel',
            name='percurso',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultado', to='api_s.percursocorrida'),
        ),
        migrations.AddConstraint(
            model_name='arquivoexcel',
            constraint=models.CheckConstraint(condition=models.Q(('corrida__isnull', False), ('percurso__isnull', False), _connector='OR'), name='resultado_exige_corrida_ou_percurso'),
        ),
    ]
