# Generated by Django 5.2.7 on 2026-06-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0058_arquivoexcel_corrida_alter_arquivoexcel_percurso_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagemBase',
        ),
    ]
