# Generated by Django 5.2.7 on 2026-06-29 20:45

from django.db import migrations, models


def preencher_distancia_corredores_antigos(apps, schema_editor):
    Corredor = apps.get_model("api_s", "Corredor")

    corredores = (
        Corredor.objects
        .select_related("arquivo__percurso")
        .filter(arquivo__percurso__isnull=False)
    )
    for corredor in corredores.iterator(chunk_size=500):
        corredor.distancia = corredor.arquivo.percurso.nome or "Geral"
        corredor.save(update_fields=["distancia"])


class Migration(migrations.Migration):

    dependencies = [
        ('api_s', '0059_delete_imagembase'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='distancia',
            field=models.CharField(blank=True, db_index=True, default='Geral', max_length=50),
        ),
        migrations.RunPython(
            preencher_distancia_corredores_antigos,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='corredor',
            index=models.Index(fields=['arquivo', 'distancia', 'colocacao'], name='api_s_corre_arquivo_d99654_idx'),
        ),
    ]
