# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_s", "0060_corredor_distancia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="enviada_cronometragem",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="data_envio_cronometragem",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="erro_envio_cronometragem",
            field=models.TextField(blank=True, null=True),
        ),
    ]
