# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_s", "0061_inscricao_cronometragem_sync"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participante",
            name="categoria",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
