# Generated by Codex on 2026-07-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_s", "0062_alter_participante_categoria_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivoexcel",
            name="corrida",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to="api_s.corrida",
            ),
        ),
        migrations.AlterField(
            model_name="arquivoexcel",
            name="percurso",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultado",
                to="api_s.percursocorrida",
            ),
        ),
    ]
