# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_s", "0063_alter_resultado_delete_behavior"),
    ]

    operations = [
        migrations.AddField(
            model_name="corrida",
            name="limite_inscritos",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
